"""Freeze strict reversible Windows code-page mappings for both desktop targets.

The page IDs follow reference/notepad-plus-plus/PowerEditor/src/EncodingMapper.cpp. Tables are API results,
not copied Windows implementation code. Regeneration requires Windows/Python;
normal builds consume the checked-in data and do not call platform codecs.
"""

import argparse
import ctypes
import hashlib
import json
from pathlib import Path
import struct
import sys

PAGES = (
    [(n, f"Windows-{n}", 1) for n in range(1250, 1259)]
    + [(28590 + n, f"ISO 8859-{n}", 1) for n in range(1, 10)]
    + [(28603, "ISO 8859-13", 1), (28605, "ISO 8859-15", 1)]
    + [(n, f"OEM {n}", 1) for n in
       (437, 720, 737, 775, 850, 852, 855, 857, 858, 860, 861, 862, 863, 865, 866, 869)]
    + [(874, "TIS-620 (Windows-874)", 1), (10007, "Macintosh Cyrillic", 1),
       (21866, "KOI8-U", 1), (20866, "KOI8-R", 1),
       (950, "Big5 (Windows-950)", 2), (936, "GBK (Windows-936)", 2),
       (932, "Shift-JIS", 2), (949, "Windows-949", 2), (51949, "EUC-KR", 2)]
)
INVALID = 0xFFFFFFFF


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    if sys.platform != "win32":
        raise SystemExit("Regeneration requires Windows; builds use the checked-in tables.")
    kernel = ctypes.WinDLL("kernel32", use_last_error=True)
    decode = kernel.MultiByteToWideChar
    decode.argtypes = [ctypes.c_uint, ctypes.c_uint, ctypes.c_char_p, ctypes.c_int,
                       ctypes.c_wchar_p, ctypes.c_int]
    decode.restype = ctypes.c_int
    encode = kernel.WideCharToMultiByte
    encode.argtypes = [ctypes.c_uint, ctypes.c_uint, ctypes.c_wchar_p, ctypes.c_int,
                       ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int)]
    encode.restype = ctypes.c_int
    output = bytearray()
    descriptors = []
    counts = {}
    for page, label, width in PAGES:
        wide = ctypes.create_unicode_buffer(4)
        narrow = ctypes.create_string_buffer(8)
        used_default = ctypes.c_int()
        decode_flags = 8
        if not decode(page, decode_flags, b"A", 1, wide, 4):
            if ctypes.get_last_error() != 1004:
                raise RuntimeError(f"Cannot decode page {page}: {ctypes.get_last_error()}")
            decode_flags = 0
        encode_flags = 0x400
        if not encode(page, encode_flags, "A", 1, narrow, 8, None, ctypes.byref(used_default)):
            if ctypes.get_last_error() != 1004:
                raise RuntimeError(f"Cannot encode page {page}: {ctypes.get_last_error()}")
            encode_flags = 0
        table = [INVALID] * (256 if width == 1 else 256 + 65536)
        canonical = {}
        for index in range(len(table)):
            original = bytes([index]) if index < 256 else (index - 256).to_bytes(2, "big")
            count = decode(page, decode_flags, original, len(original), wide, 4)
            if not count:
                error = ctypes.get_last_error()
                if error != 1113:
                    raise RuntimeError(f"Unexpected decode error for {page}: {error}")
                continue
            text = ctypes.string_at(wide, count * 2).decode("utf-16-le", "strict")
            if len(text) != 1:
                continue
            if text not in canonical:
                used_default.value = 0
                encoded_size = encode(page, encode_flags, wide, count, narrow, 8, None, ctypes.byref(used_default))
                if not encoded_size:
                    raise RuntimeError(f"Unexpected encode error for {page}: {ctypes.get_last_error()}")
                canonical[text] = None if used_default.value else narrow.raw[:encoded_size]
            if canonical[text] == original:
                table[index] = ord(text)
        if table[:128] != list(range(128)):
            raise RuntimeError(f"Page {page} does not preserve ASCII.")
        if width == 2:
            for index, value in enumerate(table[256:]):
                if value != INVALID and table[index >> 8] != INVALID:
                    raise RuntimeError(f"Ambiguous leading byte in page {page}.")
        offset = len(output) // 4
        output.extend(struct.pack(f"<{len(table)}I", *table))
        descriptors.append(f'    ({page}, "{label}", {offset}, {len(table)}),')
        counts[page] = sum(value != INVALID for value in table)
    directory = Path(__file__).resolve().parents[1] / "crates" / "io" / "src" / "codepages"
    directory.mkdir(exist_ok=True)
    catalog = (
        "// Generated by tools/generate_codepages.py. Do not edit by hand.\n"
        "pub const PAGES: &[(u16, &str, usize, usize)] = &[\n"
        + "\n".join(descriptors)
        + "\n];\npub const TABLES: &[u8] = include_bytes!(\"windows.bin\");\n"
    ).encode()
    provenance = {
        "schema": 1,
        "reference": "reference/notepad-plus-plus/PowerEditor/src/EncodingMapper.cpp",
        "source": "Windows MultiByteToWideChar/WideCharToMultiByte API observations",
        "policy": "Only exact reversible scalar mappings; no best-fit, default-character substitution or byte canonicalization.",
        "format": "Little-endian u32 Unicode scalars; 0xffffffff denotes rejected mappings.",
        "sha256": hashlib.sha256(output).hexdigest(),
        "pages": [{"id": page, "label": label, "maximum_bytes": width, "reversible_mappings": counts[page]}
                  for page, label, width in PAGES],
        "additional": {"id": 28604, "label": "ISO 8859-14", "implementation": "encoding_rs; unavailable through Windows NLS"},
    }
    files = {"catalog.rs": catalog, "windows.bin": bytes(output),
             "provenance.json": (json.dumps(provenance, indent=2) + "\n").encode()}
    for filename, contents in files.items():
        path = directory / filename
        if options.check:
            if path.read_bytes() != contents:
                raise RuntimeError(f"Mapping drift in {filename}; review Windows codec changes before regenerating.")
        else:
            path.write_bytes(contents)
    print(json.dumps({"pages": len(PAGES), "bytes": len(output),
                      "sha256": hashlib.sha256(output).hexdigest(), "reversible_mappings": counts}))


if __name__ == "__main__":
    main()
